SELECT -- *
CP.IDCITA, CP.HORA, 
P.NOMBRE || ' ' || P.APELLIDOS AS PACIENTE,
P.DNI,
M.NOMBRE || ' ' || M.APELLIDO AS MEDICO,

FROM CITAS_PACIENTES CP
INNER JOIN PACIENTES P
ON CP.IDPACIENTE = P.IDPACIENTE
INNER JOIN PERSONAL_MEDICO M
ON CP.IDMEDICO = M.IDMEDICO
;